# Setup
title:        Verify News
tagline:      Algorithmic and automated news verification
baseurl:      "/verifynews"
paginate:     1f

# About/contact
author:
  name:       Christopher Chen, Nate Brennan, Harrison Xu, Jay Khurana
  url:        https://verifynews.github.io/verifynew

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
